# -*- coding: utf-8 -*-
"""Payment Operations Analytics .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGb1VNQmvLNNJxyWIjYux3GG0n5jJgKf
"""

import pandas as pd

df = pd.read_csv('/content/payment_operations_analytics_dataset.csv')

df.head()

df.info()

df.describe()

df.isnull().sum()

df['Transaction_Status'].value_counts()

df['Payment_Method'].value_counts()

df['Failure_Reason'].value_counts()

df['Merchant_Category'].value_counts()

import matplotlib.pyplot as plt

df['Payment_Method'].value_counts().plot(kind='bar')
plt.show()

df.drop_duplicates(inplace=True)

df.to_csv('cleaned_payment_data.csv', index=False)